name: test

on:
  push:
  pull_request:

jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["latest"]
        typescript: ["5.4"]
    name: Test with TypeScript ${{ matrix.typescript }} on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn add typescript@${{ matrix.typescript }}
      - run: yarn test

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["latest"]
    name: Lint on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn prettier:check
